---
author: "University of Melbourne Centre for Cancer Research"
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    theme: cosmo
    css: style.css
    code_download: true
  rmdformats::material:
    highlight: kate
params:
  title: "UMCCR PCGR Summary Report"
description: "UMCCR PCGR Summary Report"
title: "`r params$title`"
---

```{r knitr_opts, include=F}
knitr::opts_chunk$set(
  collapse = TRUE, echo = FALSE,
  warning = FALSE, message = FALSE
)
```

```{r load_pkgs}
{
  require(tidyverse)
  require(jsonlite, include.only = c("read_json"))
  # require(dracarys) # only needed for session info
  require(glue, include.only = "glue")
  require(here, include.only = "here")
  require(knitr, include.only = "kable")
  require(DT, include.only = "datatable")
  require(fs, include.only = c("dir_ls"))
}
```

```{r data_setup, eval=FALSE}
options(width = 150)
res <- here("nogit/pcgr/2023-01-16") |>
  dir_ls(recurse = TRUE, regexp = "pcgr_metrics\\.tsv\\.gz") |>
  as_tibble_col(column_name = "path") |>
  mutate(sbj = basename(dirname(path))) |>
  # slice(1:10) |>
  rowwise() |>
  mutate(dat = list(read_tsv(path, col_types = c("dcdd")))) |>
  select(sbj, dat) |>
  unnest_wider(dat, simplify = TRUE)
res |> write_rds(here("nogit/pcgr/rds/res_2023-01-17.rds"))
```

```{r}
res <- read_rds(here("nogit/pcgr/rds/res_2023-01-17.rds"))
res
```

---

## Session Info

```{r session_info, echo=FALSE, eval=FALSE}
pkgs_of_interest <- c("base", "dracarys", "tidyverse", "tidyselect", "ggplot2", "dplyr", "tidyr", "readr")
# need dracarys for session info
si <- dracarys::session_info_kable(pkgs_of_interest)
si$si_pkg
si$si_pl
```
