# Generated by roxytest: do not edit by hand!

# File R/fs_local.R: @testexamples

test_that("Function local_list_files_dir() @ L16", {
  
  localdir <- system.file("R", package = "dracarys")
  x <- local_list_files_dir(localdir)
  expect_equal(names(x), c("bname", "size", "lastmodified", "path"))
})


test_that("Function local_list_files_filter_relevant() @ L47", {
  
  localdir <- system.file("extdata/tso", package = "dracarys")
  regexes <- tibble::tibble(regex = "multiqc_data\\.json$", fun = "MultiqcFile")
  x <- local_list_files_filter_relevant(localdir, regexes)
  expect_equal(nrow(x), 1)
})

