# Generated by roxytest: do not edit by hand!

# File R/portal_meta.R: @testexamples

test_that("Function meta_bcl_convert() @ L14", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "dracarys")
  (m <- meta_bcl_convert(pmeta))
  expect_equal(sum(!is.na(m$topup_or_rerun)), 2)
  expect_equal(length(unique(m$portal_run_id)), 4)
})


test_that("Function meta_wts_tumor_only() @ L74", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "dracarys")
  (m <- meta_wts_tumor_only(pmeta))
  expect_equal(length(unique(m$portal_run_id)), 4)
  expect_equal(length(unique(m$LibraryID)), 4)
})


test_that("Function meta_wgs_alignment_qc() @ L120", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "dracarys")
  (m <- meta_wgs_alignment_qc(pmeta))
  expect_equal("Lane" %in% colnames(m), TRUE)
})


test_that("Function meta_tso_ctdna_tumor_only() @ L162", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "dracarys")
  (m <- meta_tso_ctdna_tumor_only(pmeta))
  expect_equal(length(unique(m$portal_run_id)), 4)
})

