# Generated by roxytest: do not edit by hand!

# File R/multiqc.R: @testexamples

test_that("Function multiqc_date_fmt() @ L349", {
  
  cdate <- "2023-04-07, 09:09 UTC"
  (res1 <- multiqc_date_fmt(cdate))
  (res2 <- multiqc_date_fmt("2023-04-07"))
  (res3 <- multiqc_date_fmt("UNKNOWN"))
  expect_equal(res1, "2023-04-07T09:09:00")
  expect_equal(res2, NA_character_)
  expect_equal(res3, NA_character_)
})

