# Generated by roxytest: do not edit by hand!

# File R/dragen.R: @testexamples

test_that("Function time_metrics_process() @ L1312", {
  
  p <- system.file("extdata/wgs/SEQC-II.time_metrics.csv.gz", package = "dracarys")
  x <- TimeMetricsFile$new(p)
  (tm <- time_metrics_process(c(x, x), id = c("run1", "run2")))
  
  expect_equal(nrow(tm), 2)
})

