# Generated by roxytest: do not edit by hand!

# File R/dragen.R: @testexamples

test_that("Function dragen_subprefix() @ L876", {
  
  x1 <- "L2401290.exon_contig_mean_cov.csv"
  x2 <- "L2401290.tmb_contig_mean_cov.csv.gz"
  x3 <- "foo.bar.exon_contig_mean_cov.csv.gz"
  (s1 <- dragen_subprefix(x1, "_contig_mean_cov"))
  (s2 <- dragen_subprefix(x2, "_contig_mean_cov"))
  (s3 <- dragen_subprefix(x3, "_contig_mean_cov"))
  expect_equal(s1, "exon")
  expect_equal(s2, "tmb")
  expect_equal(s3, "bar")
})

