# Generated by roxytest: Do not edit by hand!

# File R/TimeMetricsFile.R: @testexamples

test_that("Function time_metrics_process() @ L58", {
  
  x <- system.file("extdata/wgs/SEQC-II.time_metrics.csv.gz", package = "dracarys")
  x <- TimeMetricsFile$new(x)
  (tm <- time_metrics_process(c(x, x), id = c("run1", "run2")))
  
  expect_equal(nrow(tm), 2)
})

