# Generated by roxytest: do not edit by hand!

# File R/portal_meta.R: @testexamples

test_that("Function meta_bcl_convert() @ L14", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "dracarys")
  (m <- meta_bcl_convert(pmeta))
  expect_equal(sum(!is.na(m$topup_or_rerun)), 2)
  expect_equal(length(unique(m$portal_run_id)), 4)
})


test_that("Function meta_wts_tumor_only() @ L78", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "dracarys")
  (m <- meta_wts_tumor_only(pmeta))
  expect_equal(length(unique(m$portal_run_id)), 4)
  expect_equal(length(unique(m$LibraryID)), 4)
})


test_that("Function meta_rnasum() @ L128", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "dracarys")
  (m <- meta_rnasum(pmeta))
  expect_equal(m$rnasum_dataset[1], "BRCA")
  expect_equal(basename(m$gds_outfile_rnasum_html[4]), "MDX230179.RNAseq_report.html")
})


test_that("Function meta_wgs_alignment_qc() @ L180", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "dracarys")
  (m <- meta_wgs_alignment_qc(pmeta))
  expect_equal("Lane" %in% colnames(m), TRUE)
})


test_that("Function meta_wgs_tumor_normal() @ L225", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "dracarys")
  (m <- meta_wgs_tumor_normal(pmeta))
  expect_equal("SubjectID" %in% colnames(m), TRUE)
})


test_that("Function meta_umccrise() @ L292", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "dracarys")
  (m <- meta_umccrise(pmeta))
  expect_equal(all(c("LibraryID_normal", "LibraryID_tumor") %in% colnames(m)), TRUE)
})


test_that("Function meta_tso_ctdna_tumor_only() @ L384", {
  
  pmeta <- system.file("extdata/portal_meta_top4.csv", package = "dracarys")
  (m <- meta_tso_ctdna_tumor_only(pmeta))
  expect_equal(length(unique(m$portal_run_id)), 4)
})

