# Generated by roxytest: do not edit by hand!

# File R/TblSchema.R: @testexamples

test_that("Function TblSchema() @ L22", {
  
  tbl <- tibble::tibble(
    dracarysId = "abcd1234",
    foo_num = 123,
    foo_dbl = 3.14,
    foo_chr = "foobar",
    foo_int = 35L,
    foo_date = Sys.Date()
  )
  s1 <- TblSchema$new(tbl = tbl, name = "Foo", pk = "dracarysId")
  
  expect_true(inherits(s1, c("TblSchema", "R6")))
})

