package:
  name: r-dracarys
  version: 0.5.0 # bump2version

source:
  path: ../..

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - git
  host:
    # imports
    - r-base
    - r-assertthat
    - r-dplyr
    - r-ggplot2
    - r-glue
    - r-purrr
    - r-r6
    - r-rjsonio
    - r-readr
    - r-rlang
    - r-tibble
    - r-tidyr
    # suggests
    - r-argparse
    - r-arrow
    - r-cli
    - r-emojifont
    - r-here
    - r-jsonlite
    - r-knitr
    - r-rmarkdown
    - r-scales
    - r-testthat
  run:
    # imports
    - r-base
    - r-assertthat
    - r-dplyr
    - r-ggplot2
    - r-glue
    - r-purrr
    - r-r6
    - r-rjsonio
    - r-readr
    - r-rlang
    - r-tibble
    - r-tidyr
    # suggests
    - r-argparse
    - r-arrow
    - r-cli
    - r-emojifont
    - r-here
    - r-jsonlite
    - r-knitr
    - r-rmarkdown
    - r-scales
    - r-testthat

test:
  commands:
    - $R -e "library('dracarys')"
    - dracarys.R --version

about:
  home: https://github.com/umccr/dracarys
  license: MIT
  summary: DRAGEN workflow post-processing
