---
author: "University of Melbourne Centre for Cancer Research"
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    theme: cosmo
    code_download: true
  rmdformats::material:
    highlight: kate
params:
  title: "UMCCR umccrise Summary Report"
description: "UMCCR umccrise Summary Report"
title: "`r params$title`"
---

```{r knitr_opts, include=F}
knitr::opts_chunk$set(
  collapse = TRUE, echo = FALSE,
  warning = FALSE, message = FALSE
)
```

```{css}
.navbar-brand {
  padding: 5px 15px;
}

.dropdown:hover > .dropdown-menu {
  display: block;
}
.dropdown > .dropdown-toggle:active {
  pointer-events: none;
}

.main-container {
  max-width: 1900px !important;
  margin-left: auto;
  margin-right: auto;
}

.navbar-default {
  color: #750075;
  background-color: #750075;
}
```

```{r load_pkgs}
{
  require(dplyr) # import all dplyr funcs
  require(readr, include.only = c("read_rds"))
  require(purrr, include.only = c("map"))
  require(tidyr, include.only = c("unnest"))
  require(dracarys)
  require(glue, include.only = "glue")
  require(here, include.only = "here")
  require(knitr, include.only = "kable")
  require(DT, include.only = "datatable")
  require(fs, include.only = c("dir_ls"))
  require(ggplot2, include.only = c("ggplot", "aes"))
  require(lubridate, include.only = c("as_datetime"))
  require(plotly, include.only = c("ggplotly"))
}
```

```{r data_setup, eval=FALSE}
#---- S3 ----#
s3 <- here::here(glue::glue("nogit/umccrise/rds/portal_meta/2023-09-12_pmeta_s3.rds")) |>
  readr::read_rds()
s3_get_presigned1 <- function(x, row_slice) {
  start_time <- Sys.time()
  s3_map <- x |>
    slice(row_slice) |>
    rowwise() |>
    mutate(
      s3_contents = list(s3_files_list_filter_relevant(
        s3dir = .data$dir1, presign = TRUE
      ))
    ) |>
    ungroup() |>
    tidyr::unnest("s3_contents") |>
    select(
      "SubjectID", "LibraryID_tumor", "SampleID_tumor",
      "date_utc", "type", "size", "path", "presigned_url"
    )
  end_time <- Sys.time()
  total_time <- end_time - start_time
  print(total_time)
  s3_map
}
# 2 seconds per row
s3_map1 <- s3_get_presigned1(s3, 1:100)
s3_map2 <- s3_get_presigned1(s3, 101:200)
s3_map3 <- s3_get_presigned1(s3, 201:300)
s3_map4 <- s3_get_presigned1(s3, 301:400)
s3_map5 <- s3_get_presigned1(s3, 401:449)

saveRDS(s3_map1, here("nogit/umccrise/rds/s3/map1_2023-09-12.rds"))
saveRDS(s3_map2, here("nogit/umccrise/rds/s3/map2_2023-09-12.rds"))
saveRDS(s3_map3, here("nogit/umccrise/rds/s3/map3_2023-09-12.rds"))
saveRDS(s3_map4, here("nogit/umccrise/rds/s3/map4_2023-09-12.rds"))
saveRDS(s3_map5, here("nogit/umccrise/rds/s3/map5_2023-09-12.rds"))
s3_map <- fs::dir_ls(here("nogit/umccrise/rds/s3"), regexp = "map.*rds") |>
  purrr::map(readr::read_rds) |>
  bind_rows()
saveRDS(s3_map, here("nogit/umccrise/rds/s3_map_2023-09-12.rds"))

#---- GDS ----#
token <- dracarys::ica_token_validate(Sys.getenv("ICA_ACCESS_TOKEN_PRO"))
pmeta <- here("nogit/umccrise/rds/portal_meta/2023-09-04_pmeta_final.rds") |>
  readr::read_rds()
gds_map <- pmeta |>
  rowwise() |>
  mutate(
    gds_contents = list(dracarys::gds_files_list_filter_relevant(
      gdsdir = .data$gds_outdir_umccrise, token = token, include = "PresignedUrl"
    ))
  ) |>
  ungroup() |>
  tidyr::unnest("gds_contents") |>
  select(
    "portal_run_id", "SubjectID", "LibraryID_tumor", "LibraryID_normal",
    "start", "end", "type", "bname", "size", "file_id", "path", "presigned_url"
  ) |>
  filter(type != "MultiqcFile")

saveRDS(gds_map, here("nogit/umccrise/rds/gds_map_2023-09-05.rds"))
```

```{r data_parse, eval=FALSE}
parse_files <- function(x, row_slice, rds_out) {
  start_time <- Sys.time()
  dat1 <- x |>
    slice(row_slice) |>
    rowwise() |>
    mutate(
      gen = list(dracarys::dr_func_eval(.data$type)),
      obj = list(.data$gen$new(.data$presigned_url)),
      objp = list(.data$obj$read())
    ) |>
    ungroup()
  end_time <- Sys.time()
  total_time <- end_time - start_time
  print(total_time)
  readr::write_rds(x = dat1, file = rds_out)
}

rds_path_out <- here::here("nogit/umccrise/rds/results")
#---- S3 ----#
s3_map <- readr::read_rds(here("nogit/umccrise/rds/s3_map_2023-09-12.rds"))
s0 <- parse_files(s3_map, 1:10, file.path(rds_path_out, "s0.rds"))
s1 <- parse_files(s3_map, 1:500, file.path(rds_path_out, "s1.rds"))
s2 <- parse_files(s3_map, 501:1000, file.path(rds_path_out, "s2.rds"))
s3 <- parse_files(s3_map, 1001:1500, file.path(rds_path_out, "s3.rds"))
s4 <- parse_files(s3_map, 1501:2000, file.path(rds_path_out, "s4.rds"))
s5 <- parse_files(s3_map, 2001:2245, file.path(rds_path_out, "s5.rds"))

#---- GDS ----#
gds_map <- readr::read_rds(here("nogit/umccrise/rds/gds_map_2023-09-05.rds"))
x0 <- parse_files(gds_map, 1:10, file.path(rds_path_out, "x0.rds"))
x1 <- parse_files(gds_map, 1:500, file.path(rds_path_out, "x1.rds"))
x2 <- parse_files(gds_map, 501:1000, file.path(rds_path_out, "x2.rds"))
x3 <- parse_files(gds_map, 1001:1500, file.path(rds_path_out, "x3.rds"))
x4 <- parse_files(gds_map, 1501:2000, file.path(rds_path_out, "x4.rds"))
x5 <- parse_files(gds_map, 2001:2245, file.path(rds_path_out, "x5.rds"))
```

```{r data_load}
lims_raw <- here("nogit/umccrise/rds/lims/2023-09-04_lims_raw.rds") |>
  readr::read_rds()
dat_s3 <- fs::dir_ls(here("nogit/umccrise/rds/results"), regexp = "s[1-5]{1}.rds") |>
  purrr::map(readr::read_rds) |>
  bind_rows()
dat_gds <- fs::dir_ls(here("nogit/umccrise/rds/results"), regexp = "x[1-5]{1}.rds") |>
  purrr::map(readr::read_rds) |>
  bind_rows()

dat_s3_res <- dat_s3 |>
  mutate(
    type = case_when(
      grepl("snv_2015.tsv.gz", path) ~ "UmSigsSnvFile2015",
      grepl("snv_2020.tsv.gz", path) ~ "UmSigsSnvFile2020",
      .default = .data$type
    ),
    date_utc2 = lubridate::as_datetime(.data$date_utc, format = "%Y-%m-%dT%H:%M:%S+00:00"),
    date_analysed_aest = lubridate::with_tz(.data$date_utc2, tz = "Australia/Melbourne")
  ) |>
  select(date_analysed_aest, SubjectID, LibraryID_tumor, SampleID_tumor, type, objp)
dat_gds_res <- dat_gds |>
  mutate(
    type = case_when(
      grepl("snv_2015.tsv.gz", bname) ~ "UmSigsSnvFile2015",
      grepl("snv_2020.tsv.gz", bname) ~ "UmSigsSnvFile2020",
      .default = .data$type
    ),
    date_analysed_aest = as.character(.data$end),
  ) |>
  select(date_analysed_aest, SubjectID, LibraryID_tumor, LibraryID_normal, type, objp, portal_run_id)

lims_s3 <- lims_raw |>
  filter(LibraryID %in% dat_s3_res$LibraryID_tumor) |>
  select(SubjectID, LibraryID, ExternalSubjectID, ProjectOwner, ProjectName, Type, Workflow) |>
  distinct()
lims_gds <- lims_raw |>
  filter(LibraryID %in% c(dat_gds_res$LibraryID_tumor)) |>
  select(SubjectID, LibraryID, ExternalSubjectID, ProjectOwner, ProjectName, Type, Workflow) |>
  distinct()

o1 <- dat_s3_res |>
  left_join(lims_s3, by = c("SubjectID", "LibraryID_tumor" = "LibraryID"))
#################### UP TO HERE^ ###########################################

o2 <- dat_gds_res |>
  left_join(lims_gds, by = c("SubjectID", "LibraryID_tumor" = "LibraryID")) |>
  mutate(
    url = glue("https://portal.umccr.org/subjects/{.data$SubjectID}/overview"),
    sbj_url = glue("<a href={url}>{.data$SubjectID}</a>"),
    url = glue("<a href={url}>{.data$url}</a>"),
    portal_run_id = glue("dr.{portal_run_id}")
  ) |>
  rename(portal_url = url)

dt_view <- function(x, scroll_y = 1000, ...) {
  x |>
    mutate(across(where(is.character), as.factor)) |>
    DT::datatable(
      filter = list(position = "top", clear = FALSE, plain = TRUE),
      class = "cell-border display compact",
      rownames = TRUE,
      extensions = c("Scroller", "Buttons", "KeyTable", "FixedColumns"),
      options = list(
        scroller = TRUE, scrollY = scroll_y, scrollX = TRUE,
        autoWidth = FALSE, keys = TRUE,
        buttons = c("csv", "copy"), dom = "Blfrtip",
        fixedColumns = TRUE
      ),
      escape = FALSE,
      ...
    )
}

qcsum <- o2 |>
  filter(type == "UmQcSumFile") |>
  tidyr::unnest_wider(objp)
hrd_chord <- o2 |>
  filter(type == "UmChordTsvFile") |>
  tidyr::unnest_wider(objp) |>
  select(portal_run_id,
    # chord_p_hrd = p_hrd,
    chord_hr_status = hr_status,
    chord_hrd_type = hrd_type,
    chord_p_BRCA1 = p_BRCA1,
    chord_p_BRCA2 = p_BRCA2
  )
# don't need hrdetect details
# hrd_hrdetect <- o2 |>
#   filter(type == "UmHrdetectTsvFile") |>
#   unnest_wider(objp) |>
#   select(portal_run_id, hrdetect_prob = Probability)
sigs_2015 <- o2 |>
  filter(type == "UmSigsSnvFile2015") |>
  tidyr::unnest_wider(objp) |>
  select(-c(type)) |>
  tidyr::unnest_longer(col = c(Rank, Signature, Contribution, RelFreq))
sigs_2020 <- o2 |>
  filter(type == "UmSigsSnvFile2020") |>
  tidyr::unnest_wider(objp) |>
  select(-c(type)) |>
  tidyr::unnest_longer(col = c(Rank, Signature, Contribution, RelFreq))
```

## umccrise Results

```{r final_tab}
cols_select1 <- c(
  "date_analysed_aest", "SubjectID", "sbj_url", "LibraryID_tumor", "ExternalSubjectID",
  "ProjectOwner", "ProjectName", "Type", "Workflow", "LibraryID_normal",
  "hrd_chord", "hrd_hrdetect",
  "chord_hr_status", "chord_hrd_type", "chord_p_BRCA1", "chord_p_BRCA2",
  "qc_status_hmf", "sex_hmf", "purity_hmf", "ploidy_hmf", "msi_hmf",
  "msi_mb_hmf", "contamination_hmf",
  "deleted_genes_hmf", "tmb_hmf", "tml_hmf", "wgd_hmf", "hypermutated",
  "bpi_enabled", "portal_run_id", "portal_url"
)
# signatures
dsig <- bind_rows(list(s2015 = sigs_2015, s2020 = sigs_2020), .id = "Sig_group") |>
  select(portal_run_id, Sig_group, Rank, Signature, Contribution, RelFreq)

# keep top two ranked sigs from 2015
dsig_filt <- dsig |>
  filter(
    Sig_group == "s2015"
  ) |>
  group_by(portal_run_id) |>
  mutate(tot_sig_vars = sum(Contribution)) |>
  arrange(Rank) |>
  slice_head(n = 2) |>
  # some sigs have same Rank so use explicit sig_rank
  mutate(sig_rank = row_number()) |>
  ungroup() |>
  mutate(
    sig_summary = glue("{Signature} ({RelFreq} = {Contribution} / {tot_sig_vars})")
  ) |>
  select(portal_run_id, sig_rank, sig_summary) |>
  tidyr::pivot_wider(names_from = sig_rank, values_from = sig_summary, names_prefix = "rank") |>
  mutate(sig_top2 = paste(rank1, rank2, sep = ", ")) |>
  select(portal_run_id, sig_top2)

dall <- qcsum |>
  left_join(hrd_chord, by = "portal_run_id") |>
  select(all_of(cols_select1), everything(), -c("type")) |>
  left_join(dsig_filt, by = "portal_run_id")
```

```{r join_excel_layla}
excel_all <- here("nogit/umccrise/Combined analysis Jan22_Aug23.xlsx") |>
  readxl::read_xlsx(sheet = "All")
excel_all |>
  select("...1", portal_run_id) |>
  left_join(dall |> select(portal_run_id, sig_top2)) |>
  rename(N = "...1") |>
  readr::write_csv("sigs_top2_2023-09-08.csv")
```


### HRD Results

```{r hrd_plot, fig.width=15, fig.height = 10}
p1 <- dall |>
  mutate(
    sbj = glue("{SubjectID}_{LibraryID_tumor}"),
    date = lubridate::as_datetime(date_analysed_aest, format = "%Y-%m-%d %H:%M:%S")
  ) |>
  select(
    date,
    sbj,
    chord = hrd_chord, hrdetect = hrd_hrdetect,
  ) |>
  tidyr::pivot_longer(chord:hrdetect, names_to = "method", values_to = "probability") |>
  ggplot2::ggplot(aes(x = date, y = probability, label = sbj)) +
  ggplot2::geom_point(aes(colour = method)) +
  ggplot2::geom_line(aes(group = sbj), linewidth = 0.05) +
  ggplot2::theme_bw() +
  ggplot2::ggtitle("CHORD vs. HRDetect per SubjectID")

plotly::ggplotly(p1)
```

### Signature Results

**TODO**

```{r fig.width = 15, fig.height=50, eval=FALSE}
sig_order2015 <- paste0("Sig", 1:30)
sig_order2020 <- paste0(
  "SBS",
  c(
    1:6,
    paste0(7, c("a", "b", "c", "d")),
    8:9,
    paste0(10, c("a", "b", "c", "d")),
    11:16,
    paste0(17, c("a", "b")),
    18:60,
    84:94
  )
)

d2p <- d2 |>
  # filter(Rank %in% c(1:5)) |>
  mutate(
    sbj = as.character(glue("{SubjectID}_{LibraryID_tumor}")),
    date = lubridate::as_datetime(date_analysed_aest, format = "%Y-%m-%d %H:%M:%S")
  ) |>
  select(
    date, sbj, Sig_group, Rank, Signature, Contribution, RelFreq
  ) |>
  mutate(Signature = factor(Signature, levels = c(sig_order2015, sig_order2020)))
p2 <-
  d2p |>
  ggplot2::ggplot(aes(x = Contribution, y = sbj, fill = Signature, label = sbj)) +
  ggplot2::geom_bar(position = "fill", stat = "identity") +
  ggplot2::facet_wrap(~Sig_group, ncol = 1)

plotly::ggplotly(p2)
```


## Metadata Summary {.tabset .tabset-pills}

### ProjectOwner

```{r ProjectOwner}
count(d1, ProjectOwner) |> dt_view(scroll_y = 400)
```

### ProjectName

```{r ProjectName}
count(d1, ProjectName) |> dt_view(scroll_y = 400)
```

### Type

```{r Type}
count(d1, Type) |> dt_view(scroll_y = 400)
```

### Workflow

```{r Workflow}
count(d1, Workflow) |> dt_view(scroll_y = 400)
```

</div>

---

<details>
<summary>Session Info</summary>

```{r session_info, echo=FALSE}
pkgs_of_interest <- c("base", "dracarys", "tidyverse", "tidyselect", "ggplot2", "dplyr", "tidyr", "readr")
# need dracarys for session info
si <- dracarys::session_info_kable(pkgs_of_interest)
si$si_pkg
si$si_pl
```

</details>
