name: release
on: workflow_dispatch

env:
  VERSION: '0.0.1' # versioned by bump2version

jobs:
  docker_deploy:
    name: Build and deploy Docker
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            const the_tag_name = 'refs/tags/v' + process.env.VERSION
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: the_tag_name,
              sha: context.sha
            })

      # checkout tag from above
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: v${{ env.VERSION }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            pdiakumis/dracarys:${{ env.VERSION }}
          push: true
